[project]
name = "sunkcostwhen"
version = "0.1.0"
description = "The website behind sunkcostwhen.com"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg>=3.2.5",
    "sqlalchemy>=2.0.38",
    "tornado>=6.4.2",
]

[dependency-groups]
dev = [
    "ruff>=0.9.9",
]
