FROM python:3.13-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:0.6.3 /uv /uvx /bin/
COPY pyproject.toml uv.lock ./

RUN uv sync && \
    uv cache clean && \
    rm pyproject.toml uv.lock

COPY src/websocket/ .

ENTRYPOINT ["uv", "run", "python", "app.py"]
