# Build the front-end
FROM node:22.14-alpine AS build
LABEL maintainer="david@tankski.co.uk"

WORKDIR /app

COPY package.json package-lock.json ./
COPY src/frontend/ .

RUN npm ci && \
    npm run build

# Serve the front-end
FROM nginx:1.27-alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY src/frontend/nginx.conf.template /etc/nginx/templates/default.conf.template
